### ISSUE TITLE
Usability issue - Unfortunate choice of colors

### ISSUE THREAD

**Issue by ghost** [jgrahamc/httpdiff#13]
(I know this is a bug report, but I still would like to thank you for a great tool first and foremost!)

The choice of colors does not make it easy to distinguish them properly and efficiently.

A good bright yellow is not used though it is perfect on black and better than orange which can be confused with some shades of green.

Please consider clear contrast colors compared to perceived "prettiness".

Also structural queues can be better to spot quickly compared to colors, because of color vision deficiency (for example red green vision deficiency, not blindness as it's called sometimes) but also due to different personal usage / training.

This could be simple symbols such as + - > or short words, one letter words etc. Long wordy descriptions are no substitute because they cannot be recognized on the spot, but need a more careful look.

**Comment by jgrahamc** [comment]
If you make a specific suggestion for the colors to use I'll be happy to change.
