### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by bfontaine** [jgrahamc/httpdiff#19]
Hello,

It’d be very helpful if you could tag a release so we know the code is stable and can be used. I work on [Homebrew](http://brew.sh/) and we provide a way to install `httpdiff` but we rely on the git HEAD, so we can’t provide checksums and can’t ensure users will always get the same code depending on the time they install it, making it harder for us to debug issues.

Thanks!

**Comment by jgrahamc** [comment]
https://github.com/jgrahamc/httpdiff/releases/tag/v1.0.0

**Comment by bfontaine** [comment]
I’m really late but thank you!
