### ISSUE TITLE
Support custom for HTTP headers

### ISSUE THREAD

**Issue by jacobbednarz** [jgrahamc/httpdiff#20]
I'd like to be be able to supply custom HTTP headers to both requests. I think something like the following would work:

```
$ httpdiff -header "X-Example: My value" -header "Host: example.com" https://domain.com https://domain.net
```

This would also allow you to consolidate some of the other methods like `-host` as it would be combined into the one option.

**Comment by jgrahamc** [comment]
Done

**Comment by jacobbednarz** [comment]
Awesome! Thanks a bunch. 🍰
